project_id = "oxawvjcckmbevjztyfgp"

[functions.webhook-mercado-pago]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = true

[functions.get-payment-status]
verify_jwt = true

[functions.get-admin-payments]
verify_jwt = true

[functions.get-system-stats]
verify_jwt = true

[functions.check-rate-limit]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.export-user-data]
verify_jwt = true

[functions.follow-up-pending-pix]
verify_jwt = false
