project_id = "oxawvjcckmbevjztyfgp"

[functions.webhook-mercado-pago]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.get-payment-status]
verify_jwt = false

[functions.get-admin-payments]
verify_jwt = false

[functions.get-system-stats]
verify_jwt = false
